version: "3.1"
services:
  database_0:
      image: postgres:9
      container_name: database
      volumes:
          - ./skrypty/skrypt_ver_1.sql:/docker-entrypoint-initdb.d/1-schema.sql
          - ./skrypty/create_skrypt1.sql:/docker-entrypoint-initdb.d/2-schema.sql
      ports:
          - "5432:5432"

