version: "3.1"
services:
  bot-rest:
      build: ./BotRest
      container_name: bot-rest
      ports:
          - "8080:8080"
      depends_on:
          - database_0

  database_0:
      image: postgres:10
      container_name: database
      ports:
          - "5432:5432"

